name: CI/CD Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hr_test
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/hr_test"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Install PostgreSQL Client
        run: sudo apt-get install -y postgresql-client

      - name: Install Dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop (Ruby Linter)
        run: bundle exec rubocop --format progress

      - name: Setup Database
        run: |
          bin/rails db:create db:schema:load

      - name: Run Tests
        run: |
          bin/rails db:setup
          bundle exec rspec --exclude-pattern "spec/system/**/*_spec.rb"
      
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ubuntu@54.161.211.89 << 'EOF'
          cd ~/hr_system
          git pull origin main
          bundle install
          # Set up Rails environment
          cd ~/hr_system
          bundle install
          RAILS_ENV=production bin/rails db:setup
          RAILS_ENC=production bin/rails s -d
          EOF
      

