name: CI/CD Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hr_test
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/hr_test"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Install PostgreSQL Client
        run: sudo apt-get install -y postgresql-client

      - name: Install Dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop (Ruby Linter)
        run: bundle exec rubocop --format progress

      - name: Setup Database
        run: |
          bin/rails db:create db:schema:load

      - name: Run Tests
        run: |
          bin/rails db:setup
          bundle exec rspec --exclude-pattern "spec/system/**/*_spec.rb"

      - name: Deploy EC2
        env:
          RAILS_ENV: production
        run: |
          ssh -i ~/.ssh/id_rsa -o StrickHostKEYChecking=no ubuntu@$EC2_PUBLIC_KEY << EOF
            # Update server and clone repo
            sudo apt-get update && sudo apt-get upgrade -y
            if [ ! -d "~hr_system" ]; then
              git clone git@github.com:SanRob1325/TheHRApplication.git ~/hr_system
            else
              cd ~/hr_system && git pull origin main
            fi
          
            cd ~/hr_system
            export RAILS_ENV=production
            bundle install --jobs 4 --retry 3
            yarn install --frozen-lockfile || echo "No yarn dependencies"
            bin/rails db:setup
          
            # Precompile assets and restart server
            bin/rails assets:precompile
            pkill -f pum || true
            bin/rails server -e production -b 0.0.0.0 -p 3000 &
          EOF
      

